version: '3.6'

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: <ENTER YOUR PASSWORD>
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpdbuser
      MYSQL_PASSWORD: <ENTER YOUR PASSWORD>
      VIRTUAL_HOST: <ENTER YOUR HOST NAME>
    volumes:
      - ./data_db:/var/lib/mysql
    networks:
      - wpsite

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8081:80
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: <ENTER YOUR PASSWORD>
    networks:
      - wpsite

  wordpress:
    image: wordpress:latest
    ports:
      - 8080:80
    restart: unless-stopped
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_DB_USER: wpdbuser
      WORDPRESS_DB_PASSWORD: <ENTER YOUR PASSWORD>
    volumes:
      - ./data_wordpress:/var/www/html
    networks:
      - wpsite
 
networks:
  wpsite:
