version: '3'

services:
  registry:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
      - "9001:8000"
    restart: unless-stopped
    environment:
      AGENT_SECRET: mysecrettoken
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
